### ISSUE TITLE
guidance for using this package

### ISSUE THREAD

**Issue by Toms42** [AlexisTM/multimaster#1]
I've been looking into using this package and adapting it to Noetic. My question is how does the organizer work when dealing with multiple masters? Which master runs the organizer, or if there's two, how do you ensure port assignment is consistent?

**Comment by AlexisTM** [comment]
As you can see, this package is 3y old and we decided not to continue with it. I will add a deprecated notice.

**Comment by AlexisTM** [comment]
In the meantime, if you want to play with it, the organiser is setting the unique ports via a service call on the local ROS master. 

The node can then start broadcasting the data or receiving the data over that specific port.

This was developed as to broadcast data to all robots (10 to 50) without making the network lag. One of the requirements of the superior was to keep a single "main" master. Obviously, this was not robust.

Instead, I enforced to use multimaster_fkie which avoids the single point of failure (everybody has its own master).

You could also be interested in this: [AlexisTM/rawsocket_python](https://github.com/AlexisTM/rawsocket_python) which allows sending arbitrary data to the network (custom ethertype). Using it in coordination to Zerotier allows you to very easily prioritize traffic.

**Comment by Toms42** [comment]
Ok! I ended up writing something from scratch that uses unicast udp, using your implementation as a reference for my own transport implementation. I have a proxy manager node running on each master which exposes a service on a known port to register remote services/topics, which then get assigned their own ports. It can act as a proxy for services and topics. Haven't written master discovery yet.

Unfortunately due to the circumstances it has to be closed source for now, but I may consider open sourcing it in the future.

**Comment by AlexisTM** [comment]
Good luck, once you open source it, I will add a deprecated notice and put the link to yours :) 

This repo was not used anyway at the end, thus not rugged.
